name: tictactoe
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flex_color_scheme: ^8.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  shared_preferences: ^2.3.4
  sizer: ^3.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  bloc_test: ^9.0.3

flutter:
  uses-material-design: true
